pub mod acp;
#[cfg(feature = "acp-mcp")]
pub mod acp_mcp;
pub mod adapter;
pub mod bot_turns;
pub mod config;
#[cfg(feature = "discord")]
pub mod control_db;
pub mod cron;
pub mod cursor_session;
pub mod directives;
pub mod dispatch;
pub mod error_display;
#[cfg(feature = "filestore")]
pub mod filestore;
pub mod format;
pub mod gateway;
#[cfg(feature = "discord")]
pub mod git_push_broker;
pub mod hooks;
pub mod markdown;
pub mod media;
pub mod multibot_cache;
#[cfg(feature = "pre-seed")]
pub mod pre_seed;
#[cfg(feature = "discord")]
pub mod project_command;
#[cfg(feature = "discord")]
pub mod project_registry;
pub mod reactions;
pub mod redact;
#[cfg(feature = "discord")]
pub mod remind;
#[cfg(feature = "discord")]
pub mod repository_command_queue;
pub mod secrets;
pub mod setup;
pub mod stt;
#[cfg(feature = "discord")]
pub mod task_registry;
pub mod timestamp;
pub mod trust;

#[cfg(feature = "discord")]
pub mod ambient;
#[cfg(feature = "discord")]
pub mod discord;
#[cfg(feature = "discord")]
pub mod discord_admin;
#[cfg(feature = "discord")]
pub mod discord_admin_ui;
#[cfg(feature = "discord")]
pub mod discord_queue_ui;
#[cfg(feature = "discord")]
pub mod discord_session_ui;
#[cfg(feature = "discord")]
pub mod knowledge_catalog;
#[cfg(feature = "slack")]
pub mod slack;
#[cfg(feature = "discord")]
pub mod workspace_attachment;
